// Edge Function: create-staff-account
// Creates a Supabase Auth account for a new staff member.
// Staff login: Access Code + 8-digit Staff ID + Password
// No kiosk PIN system — every user has individual credentials.
//
// Auto-injected secrets: SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, SUPABASE_ANON_KEY

import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

// Restrict CORS to the app's own origin. Falls back to a strict allowlist.
// Set ALLOWED_ORIGIN in Edge Function secrets for production.
const ALLOWED_ORIGINS = new Set([
  Deno.env.get("ALLOWED_ORIGIN") ?? "",
  "https://nexus-ghana.vercel.app",
  "http://localhost:5173",
  "http://localhost:3000",
].filter(Boolean));

function corsHeaders(req: Request) {
  const origin = req.headers.get("Origin") ?? "";
  const allowed = ALLOWED_ORIGINS.has(origin) ? origin : "https://nexus-ghana.vercel.app";
  return {
    "Access-Control-Allow-Origin": allowed,
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
    "Vary": "Origin",
  };
}

serve(async (req) => {
  const reply = (body: unknown, status = 200) => new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders(req), "Content-Type": "application/json" },
  });

  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders(req) });

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) return reply({ error: "Unauthorized" }, 401);

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey  = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const anonKey     = Deno.env.get("SUPABASE_ANON_KEY")!;

    const admin = createClient(supabaseUrl, serviceKey, { auth: { persistSession: false } });
    const caller = createClient(supabaseUrl, anonKey, {
      global: { headers: { Authorization: authHeader } },
      auth: { persistSession: false },
    });

    // 1. Verify caller has a valid session
    const { data: { user: callerUser }, error: authErr } = await caller.auth.getUser();
    if (authErr || !callerUser) return reply({ error: "Unauthorized" }, 401);

    // 2. Confirm caller owns (or is an admin member of) a business
    const { data: business } = await admin
      .from("businesses")
      .select("id")
      .eq("owner_id", callerUser.id)
      .maybeSingle();

    // Also allow staff members with Administrator role to create accounts
    let businessId = business?.id;
    if (!businessId) {
      const { data: adminStaff } = await admin
        .from("staff_members")
        .select("business_id, role")
        .eq("supabase_user_id", callerUser.id)
        .eq("status", "active")
        .maybeSingle();
      if (adminStaff?.role === "Administrator") {
        businessId = adminStaff.business_id;
      }
    }
    if (!businessId) return reply({ error: "Only business owners or administrators can create staff accounts" }, 403);

    // 3. Parse body — no PIN required, Staff ID auto-generated
    const { email, initialPassword, name, role, phone } = await req.json();
    if (!email || !name || !initialPassword) {
      return reply({ error: "email, name, and initialPassword are required" }, 400);
    }
    if (initialPassword.length < 8) {
      return reply({ error: "Initial password must be at least 8 characters" }, 400);
    }

    // 4. Create Supabase Auth account — no invite email, immediately active
    const { data: created, error: createErr } = await admin.auth.admin.createUser({
      email,
      password: initialPassword,
      email_confirm: true,
      user_metadata: { full_name: name, account_type: "staff" },
    });

    if (createErr) {
      if (createErr.message?.toLowerCase().includes("already")) {
        return reply({ error: `An account with email ${email} already exists.` }, 409);
      }
      return reply({ error: createErr.message }, 400);
    }

    const authUserId = created.user?.id;
    if (!authUserId) return reply({ error: "Failed to create auth account" }, 500);

    // 5. Insert staff_members row — staff_id auto-generated by DB trigger (8-digit unique)
    const { data: staffRow, error: insertErr } = await admin
      .from("staff_members")
      .insert({
        business_id:      businessId,
        name:             name.trim(),
        role:             role ?? "Staff",
        phone:            phone || null,
        email:            email.trim(),
        supabase_user_id: authUserId,
        status:           "active",
      })
      .select("staff_id")
      .single();

    if (insertErr) {
      // Roll back auth user to keep things consistent
      await admin.auth.admin.deleteUser(authUserId);
      return reply({ error: insertErr.message }, 400);
    }

    // Return the auto-generated Staff ID so admin can share it with the staff member
    return reply({ success: true, staffId: staffRow.staff_id });

  } catch (err: any) {
    return reply({ error: err?.message ?? "Internal server error" }, 500);
  }
});
